language: node_js
node_js:
  - "5.1.0"
matrix:
  allow_failures:
    - node_js: "5.1.0"
  fast_finish: true
script: "cd app && npm install && npm run-script test-travis"
after_script: "npm install coveralls && cat ./app/coverage/lcov.info | coveralls"
